### ISSUE TITLE
Fail to deserialize a hash 160 secret.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-sdk-java#255]
Even though hash 160 is of size 40, the server stores a 64 length string to match the other algorithms.  

{"meta":{"height":"8391","hash":"B6660C6851F97C3ACDEC6EE7CFF0207D20F2D79B4591D9570E5718261083F369","merkleComponentHash":"B6660C6851F97C3ACDEC6EE7CFF0207D20F2D79B4591D9570E5718261083F369","index":0,"id":"5E69C0140889D67E2F43ECBE"},"transaction":{"signature":"FF519899158B58C3609100111155AF5104922B8007478BCE768E05D9067DFBD39485B3F5662AD30F654A01D4A8BE4F9E0C19D7321105804713FA39FD0078F503","signerPublicKey":"76FA88F03F1E4B73E08BDC2E7201FC423E2212E9CFCA2AA6AB9F1A7FC9C46CEE","version":1,"network":152,"type":16722,"maxFee":"21000","deadline":"10565539414","duration":"5","mosaicId":"3F724C2973610971","amount":"10000000","hashAlgorithm":2,"secret":"33FB0F0C69AA7E3ADFFCECD684E9D1237D29ED4A000000000000000000000000","recipientAddress":"9891A56D466B391DD87BAFAA6F1EFEC68B270A9EEFB80AFD27"}}

    /**
     * Validate hash algorithm and hash have desired format
     *
     * @param hashType Hash type
     * @param input Input hashed
     * @return boolean when format is correct
     */
    public static boolean validator(LockHashAlgorithmType hashType, String input) {
        if (hashType == LockHashAlgorithmType.SHA3_256 && input.matches(VALIDATOR_REGEX)) {
            return input.length() == 64;
        } else if (hashType == LockHashAlgorithmType.KECCAK_256 && input.matches(VALIDATOR_REGEX)) {
            return input.length() == 64;
        } else if (hashType == LockHashAlgorithmType.HASH_160 && input.matches(VALIDATOR_REGEX)) {
            return input.length() == 40;
        } else if (hashType == LockHashAlgorithmType.HASH_256 && input.matches(VALIDATOR_REGEX)) {
            return input.length() == 64;
        }
        return false;
    }

    public int getValue() {
        return value;
    }
}

java.util.concurrent.ExecutionException: io.nem.symbol.sdk.api.RepositoryCallException: IllegalArgumentException: HashType and Secret have incompatible length or not hexadecimal string
	at io.reactivex.internal.observers.FutureObserver.get(FutureObserver.java:85) ~[rxjava-2.1.7.jar:?]
	at io.nem.symbol.automationHelpers.helper.TransactionHelper.getTransaction(TransactionHelper.java:111) ~[test-classes/:?]
	at io.nem.symbol.automationHelpers.helper.TransactionHelper.waitForStatusAndGetTransaction(TransactionHelper.java:235) ~[test-classes/:?]
	at io.nem.symbol.automationHelpers.helper.TransactionHelper.getConfirmedTransaction(TransactionHelper.java:126) ~[test-classes/:?]
	at io.nem.symbol.automationHelpers.helper.TransactionHelper.lambda$waitForTransactionToComplete$3(TransactionHelper.java:248) ~[test-classes/:?]
	at io.nem.symbol.automationHelpers.helper.TransactionHelper.lambda$waitForTransaction$4(TransactionHelper.java:270) ~[test-classes/:?]
	at io.nem.symbol.sdk.infrastructure.directconnect.dataaccess.common.RetryCommand.run(RetryCommand.java:75) [classes/:?]
	at io.nem.symbol.automationHelpers.helper.TransactionHelper.waitForTransaction(TransactionHelper.java:267) [test-classes/:?]
	at io.nem.symbol.automationHelpers.helper.TransactionHelper.waitForTransactionToComplete(TransactionHelper.java:247) [test-classes/:?]
	at io.nem.symbol.automationHelpers.helper.TransactionHelper.signAndAnnounceTransactionAndWait(TransactionHelper.java:384) [test-classes/:?]
	at io.nem.symbol.automationHelpers.helper.SecretLockHelper.submitSecretLockTransactionAndWait(SecretLockHelper.java:124) [test-classes/:?]
	at io.nem.symbol.automation.crosschainswap.ExchangeAssetsAcrossDifferentBlockchains.createSecretLockForMosaic(ExchangeAssetsAcrossDifferentBlockchains.java:89) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at cucumber.runtime.Utils$1.call(Utils.java:32) [cucumber-core-2.3.1.jar:?]
	at cucumber.runtime.Timeout.timeout(Timeout.java:16) [cucumber-core-2.3.1.jar:?]
	at cucumber.runtime.Utils.invoke(Utils.java:26) [cucumber-core-2.3.1.jar:?]
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37) [cucumber-java-2.3.1.jar:?]
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40) [cucumber-core-2.3.1.jar:?]
	at cucumber.api.TestStep.executeStep(TestStep.java:102) [cucumber-core-2.3.1.jar:?]
	at cucumber.api.TestStep.run(TestStep.java:83) [cucumber-core-2.3.1.jar:?]
	at cucumber.api.TestCase.run(TestCase.java:58) [cucumber-core-2.3.1.jar:?]
	at cucumber.runner.Runner.runPickle(Runner.java:80) [cucumber-core-2.3.1.jar:?]
	at cucumber.runtime.Runtime.runFeature(Runtime.java:119) [cucumber-core-2.3.1.jar:?]
	at cucumber.runtime.Runtime.run(Runtime.java:104) [cucumber-core-2.3.1.jar:?]
	at cucumber.api.cli.Main.run(Main.java:36) [cucumber-core-2.3.1.jar:?]
	at cucumber.api.cli.Main.main(Main.java:18) [cucumber-core-2.3.1.jar:?]
Caused by: io.nem.symbol.sdk.api.RepositoryCallException: IllegalArgumentException: HashType and Secret have incompatible length or not hexadecimal string
	at io.nem.symbol.sdk.infrastructure.vertx.AbstractRepositoryVertxImpl.exceptionHandling(AbstractRepositoryVertxImpl.java:66) ~[symbol-sdk-vertx-client-0.17.0-20200306.100509-6.jar:?]
	at io.nem.symbol.sdk.infrastructure.vertx.AbstractRepositoryVertxImpl.lambda$onError$0(AbstractRepositoryVertxImpl.java:95) ~[symbol-sdk-vertx-client-0.17.0-20200306.100509-6.jar:?]
	at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onError(ObservableOnErrorNext.java:91) ~[rxjava-2.1.7.jar:?]
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100) ~[rxjava-2.1.7.jar:?]
	at io.reactivex.internal.observers.BasicFuseableObserver.fail(BasicFuseableObserver.java:110) ~[rxjava-2.1.7.jar:?]
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:61) ~[rxjava-2.1.7.jar:?]
	at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onNext(ObservableOnErrorNext.java:68) ~[rxjava-2.1.7.jar:?]
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:59) ~[rxjava-2.1.7.jar:?]
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:41) ~[vertx-rx-java2-3.5.0.jar:?]
	at io.nem.symbol.sdk.openapi.vertx.invoker.ApiClient.lambda$buildResponseHandler$7(ApiClient.java:570) ~[symbol-openapi-vertx-client-0.8.5.jar:?]
	at io.vertx.ext.web.client.impl.HttpRequestImpl.lambda$null$1(HttpRequestImpl.java:238) ~[vertx-web-client-3.4.2.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344) ~[vertx-core-3.5.0.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163) ~[netty-common-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[netty-common-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-common-4.1.15.Final.jar:4.1.15.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_201]
Caused by: java.lang.IllegalArgumentException: HashType and Secret have incompatible length or not hexadecimal string
	at io.nem.symbol.sdk.model.transaction.SecretLockTransactionFactory.<init>(SecretLockTransactionFactory.java:49) ~[classes/:?]
	at io.nem.symbol.sdk.model.transaction.SecretLockTransactionFactory.create(SecretLockTransactionFactory.java:72) ~[classes/:?]
	at io.nem.symbol.sdk.infrastructure.vertx.mappers.SecretLockTransactionMapper.createFactory(SecretLockTransactionMapper.java:50) ~[symbol-sdk-vertx-client-0.17.0-20200306.100509-6.jar:?]
	at io.nem.symbol.sdk.infrastructure.vertx.mappers.SecretLockTransactionMapper.createFactory(SecretLockTransactionMapper.java:36) ~[symbol-sdk-vertx-client-0.17.0-20200306.100509-6.jar:?]
	at io.nem.symbol.sdk.infrastructure.vertx.mappers.AbstractTransactionMapper.createModel(AbstractTransactionMapper.java:75) ~[symbol-sdk-vertx-client-0.17.0-20200306.100509-6.jar:?]
	at io.nem.symbol.sdk.infrastructure.vertx.mappers.AbstractTransactionMapper.map(AbstractTransactionMapper.java:67) ~[symbol-sdk-vertx-client-0.17.0-20200306.100509-6.jar:?]
	at io.nem.symbol.sdk.infrastructure.vertx.mappers.GeneralTransactionMapper.map(GeneralTransactionMapper.java:86) ~[symbol-sdk-vertx-client-0.17.0-20200306.100509-6.jar:?]
	at io.nem.symbol.sdk.infrastructure.vertx.TransactionRepositoryVertxImpl.toTransaction(TransactionRepositoryVertxImpl.java:76) ~[symbol-sdk-vertx-client-0.17.0-20200306.100509-6.jar:?]
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59) ~[rxjava-2.1.7.jar:?]
	at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onNext(ObservableOnErrorNext.java:68) ~[rxjava-2.1.7.jar:?]
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:59) ~[rxjava-2.1.7.jar:?]
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:41) ~[vertx-rx-java2-3.5.0.jar:?]
	at io.nem.symbol.sdk.openapi.vertx.invoker.ApiClient.lambda$buildResponseHandler$7(ApiClient.java:570) ~[symbol-openapi-vertx-client-0.8.5.jar:?]
	at io.vertx.ext.web.client.impl.HttpRequestImpl.lambda$null$1(HttpRequestImpl.java:238) ~[vertx-web-client-3.4.2.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344) ~[vertx-core-3.5.0.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163) ~[netty-common-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[netty-common-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) ~[netty-transport-4.1.15.Final.jar:4.1.15.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-common-4.1.15.Final.jar:4.1.15.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_201]

**Comment by fboucquez** [comment]
Hi @Wayonb, is this a rest issue? should the SDK trim out the last 24 0s?

**Comment by Wayonb** [comment]
Hi @fboucquez , I dont know but the TS SDK accounts for it...i.e. it checks for 40 or 64 length.
