### ISSUE TITLE
Fail to deserialize block info due to out of range with integer type.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-sdk-java#304]
In the catbuffer , the feeMultiplier is defined as unsigned integer but trying serialized the value into a signed integer.
There are other properties such size which can hit this issue also.
````
https://github.com/nemtech/catbuffer/blob/389c96e49961354767e8b5688a1e52cacd14e0f9/schemas/types.cats#L3

https://github.com/nemtech/symbol-openapi/blob/4882ddd7813d491deb56d5b8c8b74b93e74a682d/spec/schemas/BlockFeeMultiplier.yml#L1
ava.lang.IllegalArgumentException: JsonMappingException: Numeric value (2222212828) out of range of int (-2147483648 - 2147483647)
 at [Source: (String)"{"block":{"beneficiaryAddress":"987A08509094F316F36A339019BF75420FA28D415FA0F2AF","blockHeader_Reserved1":0,"difficulty":"52427358604364","entityBody_Reserved1":0,"feeMultiplier":2222212828,"height":"828","network":152,"previousBlockHash":"52ECA8D391AB601F382573A8A3E67F758C0A688A251A135A9B14218D6027FE4D","proofGamma":"BDBEEA9970CA3727F542A81D6D411101E412A94279CA14619DB7D5E42C85EAC1","proofScalar":"EE7EB56BE6144564019A6AFE0BB34D45A76313DB2B1A8496D197096E6632AC02","proofVerificationHash":"2D57464A"[truncated 757 chars]; line: 1, column: 180] (through reference chain: io.nem.symbol.sdk.openapi.vertx.model.BlockInfoDTO["block"]->io.nem.symbol.sdk.openapi.vertx.model.BlockDTO["feeMultiplier"]). Json payload: {"block":{"beneficiaryAddress":"987A08509094F316F36A339019BF75420FA28D415FA0F2AF","blockHeader_Reserved1":0,"difficulty":"52427358604364","entityBody_Reserved1":0,"feeMultiplier":2222212828,"height":"828","network":152,"previousBlockHash":"52ECA8D391AB601F382573A8A3E67F758C0A688A251A135A9B14218D6027FE4D","proofGamma":"BDBEEA9970CA3727F542A81D6D411101E412A94279CA14619DB7D5E42C85EAC1","proofScalar":"EE7EB56BE6144564019A6AFE0BB34D45A76313DB2B1A8496D197096E6632AC02","proofVerificationHash":"2D57464AC0C9AE1EFE874FAD0B9A6142","receiptsHash":"A1C469C5E3D0A59784038664AE3872A02796FAA778CB2541D223610EF735DB86","signature":"6BCBB178BC2E55A6ACB3B967E5BE7E871E618F94264B567AB5A34AA673BE7EA619C1F39F79389DB45971803EE21C0FA05627288DAE8C6D0A47DB9AC63E61570B","signerPublicKey":"93440C0AC857760BA0CDD30ECC4A9D1327E04B7E9448EA196CE631E50E521E92","stateHash":"18BD2FE8DD37059A4BBACF083B8500135DD6AF53BDF6D028096CA4CC9B14DBB8","timestamp":"19193568554","transactionsHash":"7C6560A40D414FC32B380297BD021BEB10A682E13CA25F4E0EAD1FFFF85F92CD","type":33091,"verifiableEntityHeader_Reserved1":0,"version":1},"meta":{"generationHash":"E3147EF942825E1E51968CDE5199C8507DAA0C16210BF896DF405900B060A1BC","hash":"D5416394CEEC63FB6DC8ADE7FBCF5509F2E6812803972443BBF80851AC937D4C"}}
	at io.nem.symbol.sdk.infrastructure.vertx.JsonHelperJackson2.handleException(JsonHelperJackson2.java:119)
	at io.nem.symbol.sdk.infrastructure.vertx.JsonHelperJackson2.parse(JsonHelperJackson2.java:84)
	at io.nem.symbol.sdk.infrastructure.vertx.JsonHelperJackson2.convert(JsonHelperJackson2.java:131)
	at io.nem.symbol.sdk.infrastructure.vertx.ListenerVertx.toBlockInfo(ListenerVertx.java:108)
	at io.nem.symbol.sdk.infrastructure.ListenerBase.handle(ListenerBase.java:86)
	at io.nem.symbol.sdk.infrastructure.vertx.ListenerVertx.lambda$null$0(ListenerVertx.java:98)
	at io.vertx.core.http.impl.WebSocketImplBase.handleFrame(WebSocketImplBase.java:262)
	at io.vertx.core.http.impl.ClientConnection.handleWsFrame(ClientConnection.java:397)
	at io.vertx.core.http.impl.ClientHandler.handleMessage(ClientHandler.java:111)
	at io.vertx.core.http.impl.ClientHandler.handleMessage(ClientHandler.java:36)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:150)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:342)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:200)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2222212828) out of range of int (-2147483648 - 2147483647)
 at [Source: (String)"{"block":{"beneficiaryAddress":"987A08509094F316F36A339019BF75420FA28D415FA0F2AF","blockHeader_Reserved1":0,"difficulty":"52427358604364","entityBody_Reserved1":0,"feeMultiplier":2222212828,"height":"828","network":152,"previousBlockHash":"52ECA8D391AB601F382573A8A3E67F758C0A688A251A135A9B14218D6027FE4D","proofGamma":"BDBEEA9970CA3727F542A81D6D411101E412A94279CA14619DB7D5E42C85EAC1","proofScalar":"EE7EB56BE6144564019A6AFE0BB34D45A76313DB2B1A8496D197096E6632AC02","proofVerificationHash":"2D57464A"[truncated 757 chars]; line: 1, column: 180] (through reference chain: io.nem.symbol.sdk.openapi.vertx.model.BlockInfoDTO["block"]->io.nem.symbol.sdk.openapi.vertx.model.BlockDTO["feeMultiplier"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1714)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at io.nem.symbol.sdk.infrastructure.vertx.JsonHelperJackson2.parse(JsonHelperJackson2.java:82)
	... 31 more
Caused by: com.fasterxml.jackson.core.exc.InputCoercionException: Numeric value (2222212828) out of range of int (-2147483648 - 2147483647)
 at [Source: (String)"{"block":{"beneficiaryAddress":"987A08509094F316F36A339019BF75420FA28D415FA0F2AF","blockHeader_Reserved1":0,"difficulty":"52427358604364","entityBody_Reserved1":0,"feeMultiplier":2222212828,"height":"828","network":152,"previousBlockHash":"52ECA8D391AB601F382573A8A3E67F758C0A688A251A135A9B14218D6027FE4D","proofGamma":"BDBEEA9970CA3727F542A81D6D411101E412A94279CA14619DB7D5E42C85EAC1","proofScalar":"EE7EB56BE6144564019A6AFE0BB34D45A76313DB2B1A8496D197096E6632AC02","proofVerificationHash":"2D57464A"[truncated 757 chars]; line: 1, column: 190]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInputCoercion(ParserMinimalBase.java:601)
	at com.fasterxml.jackson.core.base.ParserMinimalBase.reportOverflowInt(ParserMinimalBase.java:570)
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:889)
	at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:802)
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:646)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:472)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:452)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	... 39 more
````

**Comment by fboucquez** [comment]
Great catch @Wayonb. My models depend on the open API aspect. I've created a PR revisiting all the possible unit32. Once that PR is merged, I'll generate the new clients and push an SDK fix
