### ISSUE TITLE
MetadataTransaction scoped key is convert to unsigned value on creation but not on retrieval.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-sdk-java#309]
The meta scoped key is converted to unsigned value here
https://github.com/nemtech/symbol-sdk-java/blob/86885315545be84e0d7c630b0563b5b1598c7b69/sdk-core/src/main/java/io/nem/symbol/sdk/infrastructure/BinarySerializationImpl.java#L696

The same is not done when trying to retrieve the metadata information from the database causing it to fail.  They should be consistent.

https://github.com/nemtech/symbol-sdk-java/blob/9381dfe17821109496e059bafa55ef5f273bb474/sdk-vertx-client/src/main/java/io/nem/symbol/sdk/infrastructure/vertx/MetadataRepositoryVertxImpl.java#L98

````
      io.nem.symbol.sdk.api.RepositoryCallException: ApiException: Conflict - 409 - InvalidArgument - key has an invalid format
	at io.nem.symbol.sdk.infrastructure.vertx.AbstractRepositoryVertxImpl.exceptionHandling(AbstractRepositoryVertxImpl.java:72)
	at io.nem.symbol.sdk.infrastructure.vertx.AbstractRepositoryVertxImpl.lambda$onError$0(AbstractRepositoryVertxImpl.java:101)
	at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onError(ObservableOnErrorNext.java:91)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onError(SingleToObservable.java:65)
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:46)
	at io.nem.symbol.sdk.openapi.vertx.invoker.ApiClient.lambda$buildResponseHandler$7(ApiClient.java:599)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$0(HttpContext.java:125)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at ✽.Sarah should have her "college certificate" attached to the account by Bob(io/nem/symbol/metadata/add_metadata_to_account.feature:17)
Caused by: java.lang.IllegalArgumentException: Original call
	at io.nem.symbol.sdk.infrastructure.vertx.AbstractRepositoryVertxImpl.call(AbstractRepositoryVertxImpl.java:58)
	at io.nem.symbol.sdk.infrastructure.vertx.MetadataRepositoryVertxImpl.handleOne(MetadataRepositoryVertxImpl.java:173)
	at io.nem.symbol.sdk.infrastructure.vertx.MetadataRepositoryVertxImpl.getAccountMetadataByKeyAndSender(MetadataRepositoryVertxImpl.java:103)
	at io.nem.symbol.automation.metadata.AccountMetadata.verifyDocument(AccountMetadata.java:137)
	at io.nem.symbol.automation.metadata.AccountMetadata.verifyDigitDocument(AccountMetadata.java:175)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at cucumber.runtime.Utils$1.call(Utils.java:32)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:26)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:37)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40)
	at cucumber.api.TestStep.executeStep(TestStep.java:102)
	at cucumber.api.TestStep.run(TestStep.java:83)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
````

**Comment by fboucquez** [comment]
Hi @Wayonb 

It seems like rest is storing and returning the value in hex. The java SDK always works with BigInteger by converting it from/to hex when talking to rest.  

https://github.com/nemtech/symbol-sdk-java/blob/9381dfe17821109496e059bafa55ef5f273bb474/sdk-vertx-client/src/main/java/io/nem/symbol/sdk/infrastructure/vertx/MetadataRepositoryVertxImpl.java#L101

https://github.com/nemtech/symbol-sdk-java/blob/9381dfe17821109496e059bafa55ef5f273bb474/sdk-vertx-client/src/main/java/io/nem/symbol/sdk/infrastructure/vertx/MetadataRepositoryVertxImpl.java#L189

As far as I can see is not doing long conversion that may overflow. Is the big integer key that is sent to getAccountMetadataByKeyAndSender negative? Maybe the overflow happens in the clients/tests? I could force a fix in the sdk by making any BigInteger positive before converting it to hex but I'm not sure. It seems more like a client bug

**Comment by Wayonb** [comment]
Hey @fboucquez 

I had a test that is generating random long value for the meta key which was then converted to BigInteger(using the valueOf()).  When the long value is negative(BigInteger is also negative), the metadata was created successful.  Using the same BigInteger value(negative) to retrieve the metadata will fail. So maybe the issue is on the metadata create?  Or it might be the toHex(key) above.  I will have to debug it some more.

**Comment by fboucquez** [comment]
Maybe your test can call SerializationUtils.toUnsignedBigInteger?

**Comment by fboucquez** [comment]
What I'm going to do is reject any negative value when serializing transactions. Users would need to have a valid positive BigInteger/Long before announcing any uint64/unit32 value. @Wayonb what do you think?

**Comment by Wayonb** [comment]
Sounds good.
