### ISSUE TITLE
The transaction size gets returned by rest but not use in the SDK.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-sdk-java#310]
The getSize() method should return the size from mongodb when posibile?  

I didnt see size as part of the JS SDK either.

```
{
   "meta":{
      "height":"1",
      "hash":"0C22CF66C6AE2CCCC32EC66ED1DED2F13A9697485726E42551ABE5308E87E3C0",
      "merkleComponentHash":"0C22CF66C6AE2CCCC32EC66ED1DED2F13A9697485726E42551ABE5308E87E3C0",
      "index":10
   },
   "transaction":{
      "size":176,
      "signature":"D42AD0939FDAB4CB93C33A72C0CF3B1A6AA3FB3C97FF919BE710B3FB8BE4A6B27285479AF92C149CA8BAD090DB8F32A99F1034EB2E7C16CE27745E7B4D6D5903",
      "signerPublicKey":"BBDC6D4228E7A9646643B88B3F60219EF03EAE65C3BD0BB92C9BA72D7FC60655",
      "version":1,
      "network":152,
      "type":16724,
      "maxFee":"0",
      "deadline":"1",
      "recipientAddress":"9891151EF283D8962CDF2B1F5A0D2283254A181EC93F147A",
      "mosaics":[
         {
            "id":"E74B99BA41F4AFEE",
            "amount":"391598771800000"
         }
      ]
   },
   "id":"5EFA6B493CFBDF02F0179A7E"
}
```

```
      java.lang.IllegalArgumentException: Size cannot be resolved from partially loaded or incomplete transactions.
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
	at io.nem.symbol.sdk.infrastructure.BinarySerializationImpl.getSize(BinarySerializationImpl.java:327)
	at io.nem.symbol.sdk.model.transaction.Transaction.getSize(Transaction.java:161)

```

**Comment by rg911** [comment]
@Wayonb This is the WS payload not rest API payload. The transaction endpoint never returns size.

**Comment by fboucquez** [comment]
It seems like rest does return the size in the transaction endpoints. 

![image](https://user-images.githubusercontent.com/5390558/86132603-7e5f9500-babd-11ea-816f-e6177ad43504.png)
![image](https://user-images.githubusercontent.com/5390558/86132610-815a8580-babd-11ea-802d-3f9855806dd5.png)

**Comment by rg911** [comment]
hmm. I thought they put  size in the meta. But will create an issue on ts as well. Currently the transaction only has a size getter. will need to add a setter as well.

**Comment by fboucquez** [comment]
Reopening, Java fix is still in PR.
