### ISSUE TITLE
Unable to verify address resolution statement hash in the block.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-sdk-java#323]
I am not sure where the failure here is.  The hash looks correct so maybe the endpoint?

Repro steps:

1. Send a transfer transaction to an alias.  
2. Try to verify the address resolution in the block

````
    final String resolvedAddressHash =
        addressResolutionStatement.get().generateHash(getTestContext().getNetworkType());
    final BlockService blockService = new BlockServiceImpl(getTestContext().getRepositoryFactory());
    final boolean found =
        blockService
            .isValidStatementInBlock(
                transferTransaction.getTransactionInfo().get().getHeight(), resolvedAddressHash)
            .blockingFirst();
````

````
io.nem.symbol.sdk.api.RepositoryCallException: ApiException: Not Found - 404 - ResourceNotFound - /blocks/17822/statements/B7AB61F24D2D68F5A3B5553A84F3793BE8E23C139FBD88D09670BD723047EE8C/merkle does not exist
	at io.nem.symbol.sdk.infrastructure.vertx.AbstractRepositoryVertxImpl.exceptionHandling(AbstractRepositoryVertxImpl.java:74)
	at io.nem.symbol.sdk.infrastructure.vertx.AbstractRepositoryVertxImpl.lambda$onError$0(AbstractRepositoryVertxImpl.java:103)
	at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onError(ObservableOnErrorNext.java:91)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onError(SingleToObservable.java:65)
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:46)
	at io.nem.symbol.sdk.openapi.vertx.invoker.ApiClient.lambda$buildResponseHandler$7(ApiClient.java:599)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$0(HttpContext.java:125)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Original call
	at io.nem.symbol.sdk.infrastructure.vertx.AbstractRepositoryVertxImpl.call(AbstractRepositoryVertxImpl.java:60)
	at io.nem.symbol.sdk.infrastructure.vertx.BlockRepositoryVertxImpl.getMerkleReceipts(BlockRepositoryVertxImpl.java:101)
	at io.nem.symbol.sdk.infrastructure.BlockServiceImpl.isValidStatementInBlock(BlockServiceImpl.java:70)
````

**Comment by fboucquez** [comment]
Can you try singular block path?

`/block/17822/statements/B7AB61F24D2D68F5A3B5553A84F3793BE8E23C139FBD88D09670BD723047EE8C/merkle`

https://github.com/nemtech/catapult-rest/commit/ca6ad59fd941bddf023365cdf12c2c5d4004b45b

you may have an old rest version?

**Comment by Wayonb** [comment]
@fboucquez Thanks.  it seem even though I a docker image prune it did not clean up everything.
